### Site Settings ###
title               : UFO Analysis
description         : A detailed analysis of UFO sightings using Altair and Vega-Lite.
baseurl             : "/ufo-analysis"   
repository          : peteoyhh/peteoyhh.github.io/ufo-analysis
open_new_tab        : false

### Plugins ###
plugins:
  - jekyll-sitemap
  - jekyll-feed

### URL Structure ###
permalink: /:title/

### Exclude from processing ###
exclude:
  - README.md
  - "*.log"
  - "*.ipynb"

### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false
